### ISSUE TITLE
kvikio still segfaults on program termination

### ISSUE THREAD

**Issue by EricKern** [rapidsai/kvikio#497]
Hi everyone,

I'm getting a segfault when my python script terminates. This only happens when kvikio is used.

# Reproducer
`mamba env create -f img2tensor_kvikio.yaml && mamba clean -afy`
```yaml
// img2tensor_kvikio.yaml
name: img2tensor
channels:
  - pytorch
  - nvidia
  - rapidsai
  - conda-forge
dependencies:
  - notebook
  - tifffile
  - python=3.11
  - pytorch
  - pytorch-cuda=12.4
  - kvikio
  ````

bug.py
```python
import kvikio

file_name = 'file0.txt'

fd = kvikio.CuFile(file_name, "w")
fd.close()
```
I'm running in a kubernetes environment. We use the open kernel driver 535.183.01

I assumed this #462  has fixed the issue but it seems there is more to it.

You can find the concretized environment here:
[exported_img2tensor_kvikio.txt](https://github.com/user-attachments/files/17374447/exported_img2tensor_kvikio.txt)

It uses kvikio 24.10 which should include the previously mentioned PR.

**Comment by jakirkham** [comment]
Could you please slim the environment further like so and retry?

```yaml
# filename: kvikio2410_cuda122.yaml
name: kvikio2410_cuda122
channels:
  - rapidsai
  - conda-forge
dependencies:
  - cuda-version=12.2
  - python=3.11
  - kvikio=24.10
```

Asking as there are mismatching CUDA versions in the reproducing environment. Plus some extra bits that appear unused in the example. So would like to simplify further to avoid other potential issues
